# Generated by Django 5.1.1 on 2024-10-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employer', 'Employer'), ('Admin', 'Admin')], default='Candidate', max_length=10),
        ),
    ]
